# Generated by Django 3.2 on 2023-05-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_rental_return_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='return_due_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='returned',
        ),
    ]
