# Generated by Django 3.2 on 2023-05-15 08:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20230515_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 8, 23, 6, 352705, tzinfo=utc)),
        ),
    ]
