# Generated by Django 3.2 on 2023-05-15 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20230515_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 18, 0, 21, 62971)),
        ),
    ]
