# Generated by Django 3.2 on 2023-05-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_rental_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 23, 23, 6, 858118)),
        ),
    ]
