# Generated by Django 3.2 on 2023-05-16 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_rental_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 23, 46, 9, 290465)),
        ),
    ]
